# Generated by Django 4.0.1 on 2023-09-30 17:11

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('username', models.CharField(help_text='Un nombre corto que se usará para identificarte de forma única en la plataforma.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Proporcione un nombre de usuario válido. Este valor debe contener solo letras, números y los caracteres: @/./+/-/_.', 'inválido')], verbose_name='Nombre de usuario')),
                ('tipo_usuario', models.CharField(choices=[('administrativo', 'Administrativo'), ('instructor', 'Instructor'), ('alumno', 'Alumno')], max_length=20, verbose_name='Tipo de Usuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Equipo')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupos a los que pertenece este usuario.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='Permisos de usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
