# Generated by Django 4.0.1 on 2023-10-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superusuario'),
        ),
    ]
