# Generated by Django 4.0.1 on 2023-09-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('alumno_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoAlumno',
            fields=[
                ('progreso_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_progreso', models.DateField()),
                ('descripcion_progreso', models.TextField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('clase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.clase')),
            ],
        ),
    ]
