# Generated by Django 4.0.1 on 2023-10-02 20:07

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clase',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(23, 59, 59)),
        ),
        migrations.AddField(
            model_name='clase',
            name='hora_inicio',
            field=models.TimeField(default='exit'),
            preserve_default=False,
        ),
    ]
