# Generated by Django 4.0.1 on 2023-10-08 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseNatacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_id', models.IntegerField(unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('nombre_docente', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(max_length=20)),
                ('plan_elegido', models.CharField(max_length=100)),
                ('fecha_clase', models.DateField()),
                ('horas_clase', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('edad', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_inscripcion', models.DateField()),
                ('telefono_emergencia', models.CharField(max_length=15)),
                ('mensualidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('membresia_vip', models.BooleanField(default=False)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('docente_a_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('clase_natacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIENDA.clasenatacion')),
            ],
        ),
    ]
