# Generated by Django 4.0.1 on 2023-10-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='alumno_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
